### ISSUE TITLE
pip install -r requirements.txt throwing error

### ISSUE THREAD

**Issue by arunpatala** [allenai/scibert#125]
The unauthenticated git protocol on port 9418 is no longer supported.

I changed it to -e git+https://github.com/ibeltagy/allennlp@fp16_and_others#egg=allennlp 

but then the finetuning task fails with 

ArrayField.empty_field return type None is not a Field

**Comment by xyd18** [comment]
https://github.com/allenai/allennlp/issues/5217#issuecomment-846049422

**Comment by arunpatala** [comment]
Thanks
