### ISSUE TITLE
Which is it?. . . BERT is adding a word at the end or a MASK answer?

### ISSUE THREAD

**Issue by bladedsupernova** [allenai/scibert#33]
I'm working on a exciting project but need to know something fast.

I seen BERT adds a word at the end of your input, like sequence prediction, elongating your input text.

But I read that BERT has been trained at (and is a pro at) filling in the blank word mask, and in fact CANNOT do sequence prediction at the end of one's input (contradiction!!). When BERT adds a fill-in answer where the mask sits, it goes in context.

I need a tool that returns me a similar word in context (the mask ANSWER!!), but the colab tool I tried is not a mask/answer giver, ..it adds words at the endddd of my input lol!!!

I also need to know how to use it...where / what do I change....

**Comment by kyleclo** [comment]
Hi, thanks for your interest!

Regarding your comment that BERT can be used for generation, are you referring to this work?  https://arxiv.org/pdf/1902.04094.pdf
It's not obvious how to generate text from BERT as-is, you'd have to do something like Gibbs sampling as described in the linked paper.

You're correct that BERT is trained with a masked language model objective.

I'm not sure what tool you're referring to, so not sure how to help you.  My recommendation is to first see if whatever tool you're using works for BERTBase.  If it doesn't work with that, then it won't work with SciBERT.
