### ISSUE TITLE
Using SciBERT for relation extraction

### ISSUE THREAD

**Issue by mathuryash5** [allenai/scibert#35]
How do I go about using SciBERT for relation extraction from raw text?
The text is information from textbooks.

**Comment by kyleclo** [comment]
Hi, thanks for your interest!
I was wondering if you're working with the gold entities in text, or are you hoping to also extract those entities?  Either way, once you have entities, then aim to get each sentence into this format:
https://github.com/allenai/scibert/blob/master/data/text_classification/chemprot/dev.txt
```
{
  "text": "This is a sentence where this is the << first entity >> and this is the [[ second entity ]].",
  "label": "RELATION_TYPE_K",
  "metadata": []
}
```
where the two entities you want to extract a relation from is wrapped between `<< >>` or `[[ ]]` tags.  Remember to be consistent with which tags correspond to the head or tail entities.

**Comment by mathuryash5** [comment]
Hi Kyle,
I was also hoping to extract the entities.
From the example given by you I see that we require the text to have a corresponding label consisting of the relation. Is it possible to just use the relation extraction model for prediction i.e just give it text with the entity mentions wrapped?

**Comment by kyleclo** [comment]
Well the thing with relation extraction is that the model needs to be trained with specific types of entities & relations in mind.  If you're looking for something unsupervised, maybe try OpenIE? https://github.com/dair-iitd/OpenIE-standalone
