### ISSUE TITLE
Generation of scivocab

### ISSUE THREAD

**Issue by stefan-it** [allenai/scibert#38]
Hi scibert-team,

I have one question regarding to the generation of the own scivocab.

In the paper, it was mentioned that SentencePiece was used. Could you provide the parameters you used for generating the vocab?

How did you managed the conversion from the `▁` annotation to `##`, which is used in the BERT tokenizer 🤔 I would really like to train an own BERT model, but the vocab generation seems a bit complicated...

Thanks in advance,

Stefan

**Comment by stefan-it** [comment]
Oh, I just found this [`cheatsheet.txt`](https://github.com/allenai/scibert/blob/0d3c6f38db90b607eea5511d7c04b72744de8eeb/scripts/cheatsheet.txt) :heart_eyes: 

Thanks for providing it :+1:

**Comment by stefan-it** [comment]
Now the `vocab` file (generated from `SentencePieceTrainer`) looks like:

```bash
<unk>   0
<s>     0
</s>    0
er      -0
en      -1
ch      -2
▁d      -3
ei      -4
ie      -5
un      -6
```

Is this conversion to a BERT compatible vocab file correct:

* Whenever a subword starts with `▁` -> remove that prefix
* Whenever a subword does not start with `▁`, just add `##`

So the original vocab is transformed into:

```bash
##er
##en
##ch
d
##ei
##ie
##un
```

But where does these `[PAD]` and `[unused*]` entries come from in the BERT scivocab file 🤔

**Comment by acohan** [comment]
BERT allocates 100 `[unused##]` vocabulary as placeholders for application specific vocabulary. So, when adapting to another domain/application, one may replace these with common tokens in that domain. The `[PAD]` and `[UNK]` tokens are reserved to indicate padding and out-of-vocabulary tokens respectively.

**Comment by kyleclo** [comment]
It looks like this was resolved, so I'm going to close this issue, but if it wasn't @stefan-it please feel free to reopen
