### ISSUE TITLE
Pretraining a PyTorch model of BERT 

### ISSUE THREAD

**Issue by nadavborenstein** [allenai/scibert#39]
We want to pretrain BERT on a costume dataset and then use this trained model with the pytorch_pretrained_bert package. 
We saw that your repository contains a PyTorch model of pretrained sci-BERT, and wondered which tools did you use to create this?

**Comment by stefan-it** [comment]
You can convert a BERT model (trained with the official TensorFlow implementation) with the `pytorch-pretrained-BERT` library, that can be found [here](https://github.com/huggingface/pytorch-pretrained-BERT).

Here's a good example of how to use convert a trained model into a PyTorch model:

https://github.com/huggingface/pytorch-pretrained-BERT#bert-1 :)

**Comment by nadavborenstein** [comment]
Thank you for the fast and informative response! :)

**Comment by kyleclo** [comment]
@stefan-it  Thanks for your help answering these questions!
