### ISSUE TITLE
CLS ACL-ARC dataset

### ISSUE THREAD

**Issue by janguck** [allenai/scibert#40]
Can you provide data for acl-arc if you want to compare it with this article by classifying it with acl-arc dataset? 
Do I have to parse myself? 
I do not think the data after i will parsing is the same with your paper.

**Comment by stefan-it** [comment]
And you should definitely look at their website:

http://jurgens.people.si.umich.edu/citation-function/

Were you can find links to several datasets:

http://jurgens.people.si.umich.edu/citation-function/

**Comment by acohan** [comment]
In addition, the complete pre-processed acl-arc dataset including additional fields is available here:
http://github.com/allenai/scicite/

**Comment by stefan-it** [comment]
Hi,

I think you can use that script [here](https://github.com/allenai/scibert/blob/master/scripts/jurgens_to_text.py).

The ARC dataset should be found in [this](https://github.com/davidjurgens/citation-function) repository :)
