### ISSUE TITLE
SciBert Checkpoints not compatible with Bert 

### ISSUE THREAD

**Issue by PradyumnaGupta** [allenai/scibert#47]
As written in the github repo of scibert ,we can use the scibert checkpoints for Tensorflow by plugging them in the Bert code on google-research/bert ( https://github.com/google-research/bert ) but when i tried doing the same I got the following data loss error - 

`DataLossError: Unable to open table file /content/scibert_data/scibert_scivocab_uncased/bert_model.ckpt.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?`

**Comment by ibeltagy** [comment]
How are you plugging them into the BERT code? do you a code snippet or command line?

**Comment by ibeltagy** [comment]
Looks like you are using 
`--init_checkpoint=scibert_scivocab_uncased/bert_model.ckpt.data-00000-of-00001` 
but you should use the following instead 
`--init_checkpoint=scibert_scivocab_uncased/bert_model.ckpt`  (even though `bert_model.ckpt` is not actually a file. This is tf thing).

**Comment by boxabirds** [comment]
I can concur that it's a simple swap to get this running in place of BERT-large.

**Comment by boxabirds** [comment]
Sorry one parameter to tweak that I forgot -pool_layer=-1 rather than the default which is -2 that gave much better results at least with initial testing. 

Aand to be clear treat scibert as a pretrained model rather than a fine-tuning.
