### ISSUE TITLE
AllenNLP dependency and upgrade path

### ISSUE THREAD

**Issue by tecoholic** [allenai/scibert#55]
Thank you for the wonderful work on the scibert package. We have trained a model for our system to generate PICO tags and it is working great. I have a few doubts before greenlighting it for production. It would be really helpful if the authors could answer them.

The requirements.txt mentions an editable install of a specific branch from the author's fork of the official AllenNLP package. Currently, that is 240+ commits behind the official repository.
 
1. Should we just stick the requirement.txt and not bother about the official packages at all? Or is there a plan to include the work in the fork to the main project. How is it going to be handled?
2. Why the editable mode why don't we just install as a regular dependency?

**Comment by ibeltagy** [comment]
1- The official package is better if it has gradient accumulation (they have an open PR for it https://github.com/allenai/allennlp/pull/3051)

2- What do you mean by regular dependency?

**Comment by tecoholic** [comment]
About 2 -  The requirements.txt file says 

```
-e git://github.com/ibeltagy/allennlp@fp16_and_others#egg=allennlp
```

I was wondering why do we need to use -e (editable flag)? We have deployed it without the -e flag and the system is running fine. Do we need to watch out for something?
