### ISSUE TITLE
No weights.tar.gz in the models

### ISSUE THREAD

**Issue by dalevskaya** [allenai/scibert#72]
Hello,

Following the instructions on how to set uo and run SciBert, I stumbled upon the problem that the file **weights.tar.gz** isn't present in pre-trained models. However, without this file the entire execution pipeline breaks.....

**Comment by kyleclo** [comment]
Hey @dalevskaya , can you specify which model you're referring to?  We provide tensorflow, pytorch, and allennlp models

**Comment by dalevskaya** [comment]
Hi @kyleclo. I downloaded **scibert-scivocab-uncased** for Tensorflow and PyTorch. None of them contains weights.tar.gz.

**Comment by kyleclo** [comment]
What codebase are you using to load the models?  Can you show me the snippet

**Comment by ibeltagy** [comment]
looking

**Comment by ibeltagy** [comment]
AllenNLP and HuggingFace have slightly different directory architectures. If you are using AllenNLP, please download one of the "PyTorch AllenNLP Models" not the HuggingFace ones.

**Comment by dalevskaya** [comment]
Thanks @ibeltagy, @kyleclo . I found the file with weights!
