### ISSUE TITLE
Creation of setup.py

### ISSUE THREAD

**Issue by jankrepl** [allenai/scibert#83]
Hi guys!

First of all, thank your for a great project!
I would like to suggest that you create a minimal `setup.py` so that the project can be easily installed. Or is there something that is preventing you from doing this?

**Comment by ibeltagy** [comment]
You are right. If you have time, a pull request will be great.

**Comment by jankrepl** [comment]
Can you just provide an update on whether it is still necessary to get your fork of `allennlp`? I know it was discussed here #55 but I wonder whether some newer versions of `allennlp` already have the feature you mentioned?
