### ISSUE TITLE
Micro F1 Or Average F1

### ISSUE THREAD

**Issue by h-peng17** [allenai/scibert#85]
Hi, In your paper, you have reported micro F1 for Relation Extraction on chemprot dataset. But In the repo, the test metric is Average F1, I wonder how I can change Average F1 to Micro F1.

**Comment by kyleclo** [comment]
Hey @h-peng17, Micro F1 is the same as Accuracy, which should be one of the metrics returned

**Comment by h-peng17** [comment]
Thank you. I forget the dataset doesn''t have NA.
